const items=[
{id:'awarapan-2',title:"Awarapan 2",image:'https://image.tmdb.org/t/p/w500/l1rC9HMKvnKooIPVfNVN2Oukzx6.jpg',description:"Information and updates about Awarapan 2.",genre:'Action',year:'2026',status:'Available'},
{id:'reacher-season-4',title:"Reacher Season 4",image:'https://image.tmdb.org/t/p/w500/f1VCQIG2iCyOookdgOzwtUpwWC0.jpg',description:"Information and updates about Reacher season 4.",genre:'Action',year:'2026',status:'Available'},
{id:'indias-got-latent-bonus-episodes',title:"India's Got Latent Bonus Episodes",image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfVGmiJx70540NfTYQWny41mv4g8a88mI-aZ68GmXM5Q&s=10',description:"Information and updates about India's Got Latent.",genre:'Comedy',year:'2026',status:'Available'},
{id:'house-of-the-dragon-season-3',title:'House Of The Dragon Season 3',image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA15WGf9egvGCjixtcn5LqrdGaf9auAHiWLBbkfxmk4w&s=10',description:'Explore information, updates and details about House Of The Dragon.',genre:'Action / Drama',year:'2026',status:'Available'},
{id:'operation-safed-sagar',title:'Operation Safed Sagar Season 1',image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvdg-E3G5s5ZvuZWwbHo12JgknAXTm9ojVrvgQizzVZA&s',description:'Explore information, updates and details about Operation Safed Sagar.',genre:'Action',year:'2026',status:'Available'},
{id:'spiderman',title:'Spider-Man: Brand New Day',image:'https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&w=800&q=80',description:'Explore information, updates and details about Spider-Man: Brand New Day.',genre:'Action / Superhero',year:'2026',status:'Available'},
{id:'supergirl',title:'Supergirl',image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtfQNHdfSP72XlwLJV02ro-_zSXygvv9hhFB5cSlnpdA&s=10',description:'Explore information, updates and details about Supergirl.',genre:'Superhero',year:'2026',status:'Available'},
{id:'gatta-kusthi-2',title:'Gatta Kusthi 2',image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoODIhdTWgkS35k0bohgVj2Mf9FIX914mw0GRCIzWVAQ&s=10',description:'Information, updates and details about Gatta Kusthi 2.',genre:'Sports',year:'2026',status:'Available'},
{id:'dc',title:'DC',image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIDw_6scwls8bOQxyCxM7ksDRUs-svwvbZXr016NFd9g&s=10',description:'Latest information and updates about the DC project.',genre:'Action',year:'2026',status:'Available'},
{id:'ohh-my-dog',title:'Ohh My Dog',image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8sFIz6uLTVqoPKU_JN0xhsBYfoUxYAtOkw8dtZaj-6Q&s=10',description:'Information and details about Ohh My Dog.',genre:'Drama',year:'2026',status:'Available'},
{id:'the-odyssey',title:'The Odyssey',image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7iUTAgZHsH4g3E6IR7O45185m-GsNRKIgRCUJ6SYN9g&s=10',description:'Odysseus, king of Ithaca, embarks on a perilous journey to return home after the Trojan War. Crossing the Mediterranean Sea with his fellow soldiers, they soon find themselves battling not only the elements, but an array of deadly obstacles and mythical creatures along the way.',genre:'Action / Fantasy',year:'2026',status:'Available'},
{id:'musafir-cafe',title:'Musafir Cafe',image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlNd_H7YRo04SL2fBLYrPvfykmfhQYy1-zXcZIFGEZXw&s=10',description:'Three travelers lives unexpectedly intertwine. Chander and Sudha share an instant spark. With Preeti, Chander finds steady companionship built on quiet understanding and ease. Which love endures through time, and life journey.',genre:'Romance / Drama / Slice-of-life',year:'2026',status:'Available'}
];
